{
 "title": "Pi_1",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "thermal_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load" }
     ]
    }
   ]
  },
  {
   "title": "Ethernet traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "RX",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "wlan0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "TX",
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "eth0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Disk used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "query": "SELECT mean(\"value\") FROM \"df_value\" WHERE (\"instance\" = 'mnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "root" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "External Written",
     "measurement": "disk_write",
     "query": "SELECT mean(\"value\") FROM \"disk_write\" WHERE (\"instance\" = 'sda3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_octets" }
     ]
    },
    {
     "alias": "External Read",
     "measurement": "disk_read",
     "query": "SELECT mean(\"value\") FROM \"disk_write\" WHERE (\"instance\" = 'sda3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sda3" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_octets" }
     ]
    },
    {
     "alias": "SD Card Written",
     "measurement": "disk_write",
     "query": "SELECT mean(\"value\") FROM \"disk_write\" WHERE (\"instance\" = 'sda3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "mmcblk0p2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_octets" }
     ]
    }
   ]
  }
 ]
}